### ISSUE TITLE
ProfilePage so user can edit their data

### ISSUE THREAD

**Issue by lukascorona** [bufak-wiso/administration-panel#20]
ProfilePage so user can edit their data

**Comment by korsmed** [comment]
Need help with the Sagas, every time i call getUser() in the componentDidMount() Method, the screen is blank, no errors printed either in the console or the screen

**Comment by lukascorona** [comment]
resolved in [this commit](https://github.com/bufak-wiso/administration-panel/commits/_20-userProfilePage). Only open Problem is the API responding with 500.
