### ISSUE TITLE
User Workshop Overview

### ISSUE THREAD

**Issue by korsmed** [bufak-wiso/administration-panel#38]
~~The User needs a card to see, which Workshops he applied for~~
 The Userneeds an overview of the Workshops for which he was accepted

**Comment by lukascorona** [comment]
Actually, the user only needs an overview of the workshops for which he was accepted. Therefore I am changing this issue to the following.

**Comment by lukascorona** [comment]
fixed by [this commit](https://github.com/bufak-wiso/administration-panel/commit/8fb254b213733285c04b771da66fbabb343be5aa)
